---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.9
        name: traefik-ingress-lb
        ports:
        - name: web
          containerPort: 8081
          hostPort: 8081
        - name: websecure
          containerPort: 8443
          hostPort: 8443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --entrypoints.web.address=:8081
        - --entrypoints.websecure.address=:8443
        - --entrypoints.traefik.address=:8080
        - --api.insecure=true
        - --providers.kubernetescrd
        - --log.level=INFO
        volumeMounts:
        - mountPath: "/data"
          name: traefik-data
        - mountPath: "/config"
          name: traefik-config
      volumes:
      - name: traefik-data
        emptyDir: {}
      - name: traefik-config
        configMap:
          name: traefik-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":8081"
      websecure:
        address: ":8443"
      traefik:
        address: ":8080"
    api:
      insecure: true
    log:
      level: INFO
    providers:
      kubernetesCRD: {}
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8081
      name: web
    - protocol: TCP
      port: 8443
      name: websecure
    - protocol: TCP
      port: 8080
      name: admin
